/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/prison/{prisonCode}/candidate-search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve a list prisoners based in search criteria
     * @description Will return prisoners in the prison where the first or last names start with the search term or where the prisoner number is an exact match.
     *
     *           Will return up to 50 results.
     *
     *
     *     Requires one of the following roles:
     *     * ROLE_PRISONER_PAY__PRISONER_PAY_UI
     */
    get: operations['search']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/pay-status-periods': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve a list of pay status periods ordered by start date
     * @description Requires one of the following roles:
     *     * ROLE_PRISONER_PAY__PRISONER_PAY_UI
     */
    get: operations['search_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Prisoner */
    Prisoner: {
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description The prisoner's first name
       * @example Joe
       */
      firstName: string
      /**
       * @description The prisoner's last name
       * @example Bloggs
       */
      lastName: string
      /**
       * @description The prisoner's residential cell location when inside the prison
       * @example A-1-002
       */
      cellLocation?: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Pay Status Period */
    PayStatusPeriod: {
      /**
       * Format: uuid
       * @description The id. Will be a UUID
       * @example e6a19788-4f80-4923-8aff-1e5fe26a6139
       */
      id: string
      /**
       * @description The prison code
       * @example PVI
       */
      prisonCode: string
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description The prisoner's first name
       * @example Joe
       */
      firstName: string
      /**
       * @description The prisoner's last name
       * @example Bloggs
       */
      lastName: string
      /**
       * @description The prisoner's residential cell location when inside the prison
       * @example A-1-002
       */
      cellLocation?: string
      /**
       * @description The pay status type
       * @example LONG_TERM_SICK
       * @enum {string}
       */
      type: 'LONG_TERM_SICK'
      /**
       * Format: date
       * @description The start date
       * @example 2025-07-23
       */
      startDate: string
      /**
       * Format: date
       * @description The end date
       * @example 2025-09-14
       */
      endDate?: string
      /**
       * @description The user who created the pay status period
       * @example USER1
       */
      createdBy: string
      /**
       * Format: date-time
       * @description The date and time the pay status period was created
       * @example 2025-07-18T12:45:11
       */
      createdDateTime: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  search: {
    parameters: {
      query: {
        /**
         * @description The search term which
         * @example Blo
         */
        searchTerm: string
      }
      header?: never
      path: {
        /**
         * @description The prison code to search within
         * @example PVI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the list of matched prisoners */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Prisoner'][]
        }
      }
      /** @description Invalid Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  search_1: {
    parameters: {
      query: {
        /**
         * @description The latest start date the pay status periods started on
         * @example 2025-07-18
         */
        latestStartDate: string
        /**
         * @description The prison code
         * @example PVI
         */
        prisonCode: string
        /**
         * @description Whether to return results which are currently active, i.e. the end date is null or not before today
         * @example true
         */
        activeOnly?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the new prisoner status period */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PayStatusPeriod'][]
        }
      }
      /** @description Invalid Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
